In [1]:

import pandas as pd
import numpy as np

In [2]:
#Import Dataset to perform first data quality checks 
dataset=pd.read_csv('/Users/Silvia/Desktop/Capstone project/CDCHealthdata2011-2021.csv')

In [3]:
#getting column names
column_names= dataset.columns.values.tolist()
print (column_names)

['yearstart', 'yearend', 'locationabbr', 'locationdesc', 'datasource', 'class', 'topic', 'question', 'data_value_unit', 'data_value_type', 'data_value', 'data_value_alt', 'data_value_footnote_symbol', 'data_value_footnote', 'low_confidence_limit', 'high_confidence_limit', 'sample_size', 'total', 'age_years', 'education', 'gender', 'income', 'race_ethnicity', 'geolocation_address', 'geolocation_zip', 'geolocation_city', 'geolocation', 'geolocation_state', 'classid', 'topicid', 'questionid', 'datavaluetypeid', 'locationid', 'stratificationcategory1', 'stratification1', 'stratificationcategoryid1', 'stratificationid1']

In [4]:
#data quality checks, looking for missing data and determining which columns have data missing 
dataset.count()

yearstart                     88629
yearend                       88629
locationabbr                  88629
locationdesc                  88629
datasource                    88629
class                         88629
topic                         88629
question                      88629
data_value_unit                   0
data_value_type               88629
data_value                    79851
data_value_alt                79851
data_value_footnote_symbol     8778
data_value_footnote            8778
low_confidence_limit          79851
high_confidence_limit         79851
sample_size                   79851
total                          3165
age_years                     18990
education                     12660
gender                         6330
income                        22155
race_ethnicity                25320
geolocation_address               0
geolocation_zip                   0
geolocation_city                  0
geolocation                   86977
geolocation_state                 0
classid                       88629
topicid                       88629
questionid                    88629
datavaluetypeid               88629
locationid                    88629
stratificationcategory1       88620
stratification1               88620
stratificationcategoryid1     88620
stratificationid1             88620
dtype: int64

In [5]:
#Sum of null values in each column
dataset. isna(). sum()

yearstart                         0
yearend                           0
locationabbr                      0
locationdesc                      0
datasource                        0
class                             0
topic                             0
question                          0
data_value_unit               88629
data_value_type                   0
data_value                     8778
data_value_alt                 8778
data_value_footnote_symbol    79851
data_value_footnote           79851
low_confidence_limit           8778
high_confidence_limit          8778
sample_size                    8778
total                         85464
age_years                     69639
education                     75969
gender                        82299
income                        66474
race_ethnicity                63309
geolocation_address           88629
geolocation_zip               88629
geolocation_city              88629
geolocation                    1652
geolocation_state             88629
classid                           0
topicid                           0
questionid                        0
datavaluetypeid                   0
locationid                        0
stratificationcategory1           9
stratification1                   9
stratificationcategoryid1         9
stratificationid1                 9
dtype: int64

In [6]:
#sum of total null values in dataset
dataset. isna(). sum() .sum()

1091579

In [7]:
#datatype for each column

dataset.dtypes

yearstart                       int64
yearend                         int64
locationabbr                   object
locationdesc                   object
datasource                     object
class                          object
topic                          object
question                       object
data_value_unit               float64
data_value_type                object
data_value                    float64
data_value_alt                float64
data_value_footnote_symbol     object
data_value_footnote            object
low_confidence_limit          float64
high_confidence_limit         float64
sample_size                   float64
total                          object
age_years                      object
education                      object
gender                         object
income                         object
race_ethnicity                 object
geolocation_address           float64
geolocation_zip               float64
geolocation_city              float64
geolocation                    object
geolocation_state             float64
classid                        object
topicid                        object
questionid                     object
datavaluetypeid                object
locationid                      int64
stratificationcategory1        object
stratification1                object
stratificationcategoryid1      object
stratificationid1              object
dtype: object

In [8]:
#making a copy of the data 

dataset2= pd.DataFrame(dataset)
print(dataset2.head(10))

   yearstart  yearend locationabbr    locationdesc  \
0       2016     2016           AZ         Arizona
1       2016     2016           LA       Louisiana
2       2016     2016           FL         Florida
3       2016     2016           TN       Tennessee
4       2016     2016           HI          Hawaii
5       2016     2016           MN       Minnesota
6       2016     2016           AL         Alabama
7       2016     2016           DE        Delaware
8       2016     2016           AZ         Arizona
9       2016     2016           NC  North Carolina

                                   datasource                    class  \
0  Behavioral Risk Factor Surveillance System  Obesity / Weight Status
1  Behavioral Risk Factor Surveillance System  Obesity / Weight Status
2  Behavioral Risk Factor Surveillance System        Physical Activity
3  Behavioral Risk Factor Surveillance System        Physical Activity
4  Behavioral Risk Factor Surveillance System        Physical Activity
5  Behavioral Risk Factor Surveillance System  Obesity / Weight Status
6  Behavioral Risk Factor Surveillance System  Obesity / Weight Status
7  Behavioral Risk Factor Surveillance System        Physical Activity
8  Behavioral Risk Factor Surveillance System  Obesity / Weight Status
9  Behavioral Risk Factor Surveillance System  Obesity / Weight Status

                          topic  \
0       Obesity / Weight Status
1       Obesity / Weight Status
2  Physical Activity - Behavior
3  Physical Activity - Behavior
4  Physical Activity - Behavior
5       Obesity / Weight Status
6       Obesity / Weight Status
7  Physical Activity - Behavior
8       Obesity / Weight Status
9       Obesity / Weight Status

                                            question  data_value_unit  \
0  Percent of adults aged 18 years and older who ...              NaN
1  Percent of adults aged 18 years and older who ...              NaN
2  Percent of adults who engage in no leisure-tim...              NaN
3  Percent of adults who engage in no leisure-tim...              NaN
4  Percent of adults who engage in no leisure-tim...              NaN
5  Percent of adults aged 18 years and older who ...              NaN
6  Percent of adults aged 18 years and older who ...              NaN
7  Percent of adults who engage in no leisure-tim...              NaN
8  Percent of adults aged 18 years and older who ...              NaN
9  Percent of adults aged 18 years and older who ...              NaN

  data_value_type  ...  geolocation_state  classid topicid questionid  \
0           Value  ...                NaN      OWS    OWS1       Q037
1           Value  ...                NaN      OWS    OWS1       Q036
2           Value  ...                NaN       PA     PA1       Q047
3           Value  ...                NaN       PA     PA1       Q047
4           Value  ...                NaN       PA     PA1       Q047
5           Value  ...                NaN      OWS    OWS1       Q036
6           Value  ...                NaN      OWS    OWS1       Q037
7           Value  ...                NaN       PA     PA1       Q047
8           Value  ...                NaN      OWS    OWS1       Q037
9           Value  ...                NaN      OWS    OWS1       Q037

   datavaluetypeid  locationid  stratificationcategory1  \
0            VALUE           4           Race/Ethnicity
1            VALUE          22           Race/Ethnicity
2            VALUE          12                Education
3            VALUE          47                Education
4            VALUE          15              Age (years)
5            VALUE          27                Education
6            VALUE           1                   Income
7            VALUE          10           Race/Ethnicity
8            VALUE           4           Race/Ethnicity
9            VALUE          37              Age (years)

                    stratification1 stratificationcategoryid1  \
0     American Indian/Alaska Native                      RACE
1         Hawaiian/Pacific Islander                      RACE
2  Some college or technical school                       EDU
3  Some college or technical school                       EDU
4                           35 - 44                     AGEYR
5              High school graduate                       EDU
6                 Less than $15,000                       INC
7                Non-Hispanic White                      RACE
8                             Asian                      RACE
9                           25 - 34                     AGEYR

  stratificationid1
0           RACENAA
1           RACEHPI
2          EDUCOTEC
3          EDUCOTEC
4         AGEYR3544
5         EDUHSGRAD
6         INCLESS15
7           RACEWHT
8           RACEASN
9         AGEYR2534

[10 rows x 37 columns]

In [9]:
#look for duplicate Rows

dataset2.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
88624    False
88625    False
88626    False
88627    False
88628    False
Length: 88629, dtype: bool

In [10]:
#another way to look at duplicate records
dataset2.duplicated().tolist()

[False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 ...]

##queried original CSV in SQl as follows and created a new CSV

###SELECT yearstart as "Starting_Year", yearend as "Ending_year", 
locationabbr as "State_Abbrebriation" , 
locationdesc as "State", 
datasource as "Data_Source",
class as "Question_Category", 
topic as "Topic_Category",
question as "Question" ,   
data_value as "Percentage_Of_Sample",
low_confidence_limit as "Min_Confidence_Interval_95%",
high_confidence_limit as "Max_Confidence_Interval_95%",
sample_size as "Sample_Size",
age_years as "Age_range",
education as "Education",
gender as "Gender",
income as "Income",
race_ethnicity as "Race_Ethnicity",
geolocation as "Geolocation",
stratificationcategory1 as "Diversity_category",
stratification1  as "Diversity_data"
FROM "CDCHealthdata2011-2021"##

In [11]:
##Selected columns to be utilized in SQL brought in new CSV

UpdatedData=pd.read_csv('/Users/Silvia/Desktop/Updated Capstone/_CDCHealthdata2011_2021__202304032334.csv')

In [12]:
#add a calculated field- affected population from sample
UpdatedData['Affected_Population'] = UpdatedData.PERCENTAGE_OF_SAMPLE * UpdatedData.sample_size//100

In [13]:
#column names

column_names2= UpdatedData.columns.values.tolist()
print (column_names2)

['STARTING_YEAR', 'ENDING_YEAR', 'STATE_ABBREBRIATION', 'STATE', 'DATA_SOURCE', 'QUESTION_CATEGORY', 'TOPIC_CATEGORY', 'question', 'PERCENTAGE_OF_SAMPLE', 'MIN_CONFIDENCE_INTERVAL_95%', 'MAX_CONFIDENCE_INTERVAL_95%', 'sample_size', 'AGE_RANGE', 'education', 'gender', 'income', 'race_ethnicity', 'geolocation', 'DIVERSITY_CATEGORY', 'DIVERSITY_DATA', 'Affected_Population']

In [14]:
UpdatedData.head(10)

,STARTING_YEAR,ENDING_YEAR,STATE_ABBREBRIATION,STATE,DATA_SOURCE,QUESTION_CATEGORY,TOPIC_CATEGORY,question,PERCENTAGE_OF_SAMPLE,MIN_CONFIDENCE_INTERVAL_95%,...,sample_size,AGE_RANGE,education,gender,income,race_ethnicity,geolocation,DIVERSITY_CATEGORY,DIVERSITY_DATA,Affected_Population
0,2016,2016,AZ,Arizona,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,30.3,24.2,...,452.0,NaN,NaN,NaN,NaN,American Indian/Alaska Native,POINT (-111.763811277 34.86597028),Race/Ethnicity,American Indian/Alaska Native,136.0
1,2016,2016,LA,Louisiana,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Hawaiian/Pacific Islander,POINT (-92.445680071 31.312660644),Race/Ethnicity,Hawaiian/Pacific Islander,NaN
2,2016,2016,FL,Florida,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,26.1,24.5,...,10660.0,NaN,Some college or technical school,NaN,NaN,NaN,POINT (-81.928960539 28.932040377),Education,Some college or technical school,2782.0
3,2016,2016,TN,Tennessee,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,23.4,20.8,...,1612.0,NaN,Some college or technical school,NaN,NaN,NaN,POINT (-85.774490914 35.68094058),Education,Some college or technical school,377.0
4,2016,2016,HI,Hawaii,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,18.1,15.1,...,947.0,35 - 44,NaN,NaN,NaN,NaN,POINT (-157.857749403 21.304850435),Age (years),35 - 44,171.0
5,2016,2016,MN,Minnesota,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,30.4,28.7,...,3768.0,NaN,High school graduate,NaN,NaN,NaN,POINT (-94.794200503 46.355648736),Education,High school graduate,1145.0
6,2016,2016,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,26.7,22.7,...,828.0,NaN,NaN,NaN,"Less than $15,000",NaN,POINT (-86.631860762 32.840571122),Income,"Less than $15,000",221.0
7,2016,2016,DE,Delaware,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,25.0,22.8,...,2818.0,NaN,NaN,NaN,NaN,Non-Hispanic White,POINT (-75.577741168 39.008830667),Race/Ethnicity,Non-Hispanic White,704.0
8,2016,2016,AZ,Arizona,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,21.4,13.9,...,115.0,NaN,NaN,NaN,NaN,Asian,POINT (-111.763811277 34.86597028),Race/Ethnicity,Asian,24.0
9,2016,2016,NC,North Carolina,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,36.1,32.2,...,780.0,25 - 34,NaN,NaN,NaN,NaN,POINT (-79.159250463 35.466220975),Age (years),25 - 34,281.0

In [18]:
#rechecked datatypes of subset
UpdatedData.dtypes

STARTING_YEAR                    int64
ENDING_YEAR                      int64
STATE_ABBREBRIATION             object
STATE                           object
DATA_SOURCE                     object
QUESTION_CATEGORY               object
TOPIC_CATEGORY                  object
question                        object
PERCENTAGE_OF_SAMPLE           float64
MIN_CONFIDENCE_INTERVAL_95%    float64
MAX_CONFIDENCE_INTERVAL_95%    float64
sample_size                    float64
AGE_RANGE                       object
education                       object
gender                          object
income                          object
race_ethnicity                  object
geolocation                     object
DIVERSITY_CATEGORY              object
DIVERSITY_DATA                  object
Affected_Population            float64
dtype: object

In [19]:
#rechecked for null values

UpdatedData.count()

STARTING_YEAR                  88629
ENDING_YEAR                    88629
STATE_ABBREBRIATION            88629
STATE                          88629
DATA_SOURCE                    88629
QUESTION_CATEGORY              88629
TOPIC_CATEGORY                 88629
question                       88629
PERCENTAGE_OF_SAMPLE           79851
MIN_CONFIDENCE_INTERVAL_95%    79851
MAX_CONFIDENCE_INTERVAL_95%    79851
sample_size                    79851
AGE_RANGE                      18990
education                      12660
gender                          6330
income                         22155
race_ethnicity                 25320
geolocation                    86977
DIVERSITY_CATEGORY             88620
DIVERSITY_DATA                 88620
Affected_Population            79851
dtype: int64

In [25]:
UpdatedData2 = UpdatedData.rename({'STARTING_YEAR': 'Starting_Year', 'ENDING_YEAR': 'Ending_Year', 'STATE_ABBREBRIATION':'State_Abbreviation',
                                   'STATE': 'State', 'DATA_SOURCE':'Data_Source', 'QUESTION_CATEGORY':'Question_Category', 
                                   'TOPIC_CATEGORY':'Topic-Category',
                                   'question': 'Question', 'PERCENTAGE_OF_SAMPLE': 'Percentage_of_Sample', 
                                   'MIN_CONFIDENCE_INTERVAL_95%':'Min_Confidence_Interval_95%' , 
                                   'MAX_CONFIDENCE_INTERVAL_95%':'Max_Confidence_Interval_95%', 'sample_size':'Sample_Size', 
                                   'AGE_RANGE': 'Age_Range', 'education': 'Education', 'gender': 'Gender', 'income': 'Income', 
                                   'race_ethnicity': 'Race_Ethnicity','geolocation': 'GeoLocation', 
                                   'DIVERSITY_CATEGORY': 'Diversity_Category', 'DIVERSITY_DATA': 'Diversity_Data', 
                                   'Affected_Population':'Affected_Population'},axis=1)

In [26]:
UpdatedData2.tail(10)

,Starting_Year,Ending_Year,State_Abbreviation,State,Data_Source,Question_Category,Topic-Category,Question,Percentage_of_Sample,Min_Confidence_Interval_95%,...,Sample_Size,Age_Range,Education,Gender,Income,Race_Ethnicity,GeoLocation,Diversity_Category,Diversity_Data,Affected_Population
88619,2011,2011,AL,Alabama,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,35.2,30.7,...,598.0,25 - 34,NaN,NaN,NaN,NaN,POINT (-86.631860762 32.840571122),Age (years),25 - 34,210.0
88620,2015,2015,PR,Puerto Rico,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,38.1,32.6,...,421.0,NaN,NaN,NaN,"$25,000 - $34,999",NaN,POINT (-66.590149 18.220833),Income,"$25,000 - $34,999",160.0
88621,2012,2012,DC,District of Columbia,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,31.6,24.0,...,243.0,NaN,Less than high school,NaN,NaN,NaN,POINT (-77.031961127 38.890371385),Education,Less than high school,76.0
88622,2012,2012,WY,Wyoming,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,48.5,32.3,...,69.0,NaN,NaN,NaN,NaN,American Indian/Alaska Native,POINT (-108.109830353 43.235541343),Race/Ethnicity,American Indian/Alaska Native,33.0
88623,2015,2015,GU,Guam,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who achieve at least 150 min...,27.4,18.6,...,125.0,NaN,NaN,NaN,NaN,Hispanic,POINT (144.793731 13.444304),Race/Ethnicity,Hispanic,34.0
88624,2015,2015,US,National,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who achieve at least 300 min...,26.6,25.6,...,30904.0,NaN,NaN,NaN,"Less than $15,000",NaN,NaN,Income,"Less than $15,000",8220.0
88625,2013,2013,US,National,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,32.7,31.9,...,60069.0,NaN,NaN,NaN,Data not reported,NaN,NaN,Income,Data not reported,19642.0
88626,2013,2013,US,National,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,28.8,28.1,...,62562.0,NaN,NaN,NaN,"$50,000 - $74,999",NaN,NaN,Income,"$50,000 - $74,999",18017.0
88627,2014,2014,GU,Guam,Behavioral Risk Factor Surveillance System,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,29.3,25.7,...,842.0,NaN,High school graduate,NaN,NaN,NaN,POINT (144.793731 13.444304),Education,High school graduate,246.0
88628,2020,2020,US,National,Behavioral Risk Factor Surveillance System,Physical Activity,Physical Activity - Behavior,Percent of adults who engage in no leisure-tim...,30.6,29.4,...,31255.0,NaN,NaN,NaN,NaN,Hispanic,NaN,Race/Ethnicity,Hispanic,9564.0

In [ ]:
UpdatedData2.to_csv('/Users/Silvia/Desktop/Updated Capstone/')